-- MySQL Script generated by MySQL Workbench
-- 12/26/17 14:38:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema reserva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reserva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reserva` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `reserva` ;

-- -----------------------------------------------------
-- Table `reserva`.`unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`unidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`quadra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`quadra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `unidade_id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quadra_unidade_idx` (`unidade_id` ASC),
  CONSTRAINT `fk_quadra_unidade`
    FOREIGN KEY (`unidade_id`)
    REFERENCES `reserva`.`unidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`horario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_id` INT NOT NULL,
  `inicio_hora` INT NULL,
  `inicio_minuto` INT NULL,
  `duracao` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_horario_tipo1_idx` (`tipo_id` ASC),
  CONSTRAINT `fk_horario_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `reserva`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NULL,
  `telefone` VARCHAR(45) NULL,
  `observacoes` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`reserva` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quadra_id` INT NOT NULL,
  `horario_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `mensal` VARCHAR(1) NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quadra_has_horario_horario1_idx` (`horario_id` ASC),
  INDEX `fk_quadra_has_horario_quadra1_idx` (`quadra_id` ASC),
  INDEX `fk_reserva_cliente1_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_quadra_has_horario_quadra1`
    FOREIGN KEY (`quadra_id`)
    REFERENCES `reserva`.`quadra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quadra_has_horario_horario1`
    FOREIGN KEY (`horario_id`)
    REFERENCES `reserva`.`horario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `reserva`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
